version: '3.8'

services:
  customerdb:
    image: postgres:latest
    container_name: customer-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  bookdb:
    image: mysql:latest
    container_name: book-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bookdb
      MYSQL_ROOT_PASSWORD: root